#- name: Install httpd
# yum:
#   name: "{{ websvc }}"
#   state: installed
#    enabled:  

# - name: Start httpd
#  service:
#    name: "{{ websvc }}"
#    state: started 

- name: Install httpd package
  dnf:
    name: httpd
    state: latest

- name: Start and enable httpd service
  service:
     name: httpd
     enabled: true
     state: started


- include_vars: test.yml

- name: copies index.html pages
  copy:
    src: index.html
    dest: "{{webroot}}"

- name: copies jinja files
  template:
       src: httpd.conf.j2
       dest: "{{webconfig}}/web.conf"

  notify: restart_apache       
